name: mspypeline_dev
channels:
  - conda-forge
dependencies:
  - python=3.8.13
  - numpy=1.24.0
  - pandas=1.5.3
  - scipy=1.10.1
  - rpy2=3.4.5
  - tzlocal=4.3
  - ruamel_yaml=0.15.80
  - matplotlib=3.7.0
  - matplotlib-venn=0.11.9
  - adjusttext=0.7.3.1
  - scikit-learn=1.1.2
  - sphinx=5.0.2
  - ipython=8.11.0

